version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.12.1
    steps:
      - checkout
      - run: python --version
      - run:
          name: Actualizar pip
          command: |
            pip install --upgrade pip
      - run:
          name: Instalar dependencias
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Ejecutar Black
          command: |
            . venv/bin/activate
            black --check .
      - run:
          name: Ejecutar Mypy
          command: |
            . venv/bin/activate
            mypy app.py

workflows:
  version: 2
  test:
    jobs:
      - test